### ISSUE TITLE
Can't load grml.org.

### ISSUE THREAD

**Issue by raoulbhatia** [grml/grml.org#12]
grml.org responds to ping and listens on port 22.
However, the web server seems to be down.

```
$ host grml.org
grml.org has address 83.246.69.174
grml.org has IPv6 address 2a02:790:1:12::6
grml.org mail is handled by 10 mail.grml.org.
```

Thanks,
Raoul

**Comment by mika** [comment]
Jepp indeed, this was caused by a r/o filesystem which nobody of us noticed during the (pre)weekend time. Was fixed yesterday morning, thanks for reporting!
