### ISSUE TITLE
serve deb.grml.org over HTTPS

### ISSUE THREAD

**Issue by anarcat** [grml/grml.org#14]
it would be nice if the debian archive would be available over HTTPS. it would allow users to escape certain active attacks that could occur when they bootstrap the OpenPGP trust anchors for SecureApt on first setup, for example.

ideally, like the main website (#9), HTTP would  be redirected to HTTPS as well.

for reference, `apt-transport-https` is available in Debian since wheezy.

**Comment by formorer** [comment]
The Repo is now available via https
