### ISSUE TITLE
Please update grml-zsh-refcard.pdf

### ISSUE THREAD

**Issue by jkirk** [grml/grml.org#22]
The current [grml-zsh-refcard](https://grml.org/zsh/grml-zsh-refcard.pdf) was generated on 2016-01-25.

At least the keybinding for inserting a timestamp on the command line is out of date (because of grml/grml-etc-core#62, where the keybinding was changed to `CTRL-x d`).

**Comment by mika** [comment]
Thanks for noticing and reporting that!
It's sadly still not automated but a manual procedure. I just took care of it!
