### ISSUE TITLE
website scrolling dose not work on its own system

### ISSUE THREAD

**Issue by nanderer** [grml/grml.org#28]
hi there. lookes like your fork button is transparently above your scroll bar, please fix that, make it smaller or below the text area. A gif says more then a thousend words:
![Peek 2020-04-29 19-46](https://user-images.githubusercontent.com/45161625/80629240-1996a880-8a42-11ea-8468-96e784a256be.gif)

thanks in advance and keep up the good work

**Comment by jkirk** [comment]
@nanderer I just tried to reproduce this problem, but couldn't. Is still an issue, because from my POV everything looks fine.

**Comment by zeha** [comment]
I fixed a scrolling issue on master. If it's still a problem, please reopen.
